# Generated by Django 5.1.15 on 2026-06-06 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(db_index=True, help_text='GitHub login (e.g. owner slug)', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, help_text='Display name', max_length=255)),
                ('org_type', models.CharField(choices=[('org', 'Organization'), ('user', 'User')], db_index=True, default='org', max_length=10)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('html_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['login'],
            },
        ),
        migrations.CreateModel(
            name='RepoConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_type', models.CharField(choices=[('token', 'Personal Access Token (env var)'), ('github_app', 'GitHub App Installation')], default='token', max_length=20)),
                ('token_env_var', models.CharField(blank=True, help_text='Name of the env var holding the token (NOT the token itself)', max_length=255)),
                ('installation_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='dashboard.organization')),
            ],
            options={
                'ordering': ['organization', 'connection_type'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, help_text='owner/repo', max_length=512, unique=True)),
                ('owner', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_fork', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, db_index=True, max_length=100)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('html_url', models.URLField(blank=True, max_length=500)),
                ('is_tracked', models.BooleanField(db_index=True, default=True, help_text='Whether this repo is on the active ingestion watchlist')),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_etag', models.CharField(blank=True, help_text='ETag from the last repo metadata fetch (conditional requests)', max_length=255)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('open_issues_count', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='dashboard.organization')),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='RepoMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('open_pr_count', models.IntegerField(default=0)),
                ('stale_pr_count', models.IntegerField(default=0, help_text='Open PRs not updated within the staleness window')),
                ('open_issue_count', models.IntegerField(default=0)),
                ('ci_total_runs', models.IntegerField(default=0)),
                ('ci_success_count', models.IntegerField(default=0)),
                ('ci_failure_count', models.IntegerField(default=0)),
                ('ci_success_rate', models.FloatField(blank=True, help_text='Success ratio (0.0-1.0) over the sampled workflow runs', null=True)),
                ('security_alert_count', models.IntegerField(default=0)),
                ('last_release_tag', models.CharField(blank=True, max_length=255)),
                ('last_release_at', models.DateTimeField(blank=True, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dashboard.repository')),
            ],
            options={
                'ordering': ['-captured_at'],
                'get_latest_by': 'captured_at',
            },
        ),
        migrations.CreateModel(
            name='RepoDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('repo', 'Repository'), ('fleet', 'Fleet')], db_index=True, default='repo', max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(help_text='AI-generated "what needs attention" summary')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('generated_by_model', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Structured context the digest was built from')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='dashboard.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['is_tracked', 'is_archived'], name='dashboard_r_is_trac_5f42fa_idx'),
        ),
        migrations.AddIndex(
            model_name='repometricsnapshot',
            index=models.Index(fields=['repository', '-captured_at'], name='dashboard_r_reposit_48b269_idx'),
        ),
        migrations.AddIndex(
            model_name='repometricsnapshot',
            index=models.Index(fields=['ci_success_rate'], name='dashboard_r_ci_succ_475657_idx'),
        ),
        migrations.AddIndex(
            model_name='repometricsnapshot',
            index=models.Index(fields=['security_alert_count'], name='dashboard_r_securit_10a86a_idx'),
        ),
        migrations.AddIndex(
            model_name='repodigest',
            index=models.Index(fields=['scope', '-created_at'], name='dashboard_r_scope_33c6ad_idx'),
        ),
        migrations.AddIndex(
            model_name='repodigest',
            index=models.Index(fields=['severity', '-created_at'], name='dashboard_r_severit_b540dd_idx'),
        ),
    ]
