# Generated by Django 4.2.7 on 2025-11-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_type', models.CharField(choices=[('openai', 'OpenAI'), ('github', 'GitHub')], db_index=True, max_length=20)),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_type', '-created_at'], name='core_apilog_api_typ_724c9b_idx'), models.Index(fields=['status_code', '-created_at'], name='core_apilog_status__2a0c99_idx')],
            },
        ),
    ]
