# Generated by Django 5.1.14 on 2025-11-25 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Provider name (e.g., openai, xai)", max_length=50, unique=True
                    ),
                ),
                ("display_name", models.CharField(help_text="Human-readable name (e.g., OpenAI, XAI)", max_length=100)),
                (
                    "api_key",
                    models.CharField(blank=True, help_text="API key (encrypted in production)", max_length=500),
                ),
                ("base_url", models.URLField(help_text="API base URL", max_length=500)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "default_temperature",
                    models.FloatField(default=0.2, help_text="Default temperature for this provider"),
                ),
                (
                    "default_max_tokens",
                    models.IntegerField(default=2500, help_text="Default max tokens for this provider"),
                ),
                ("description", models.TextField(blank=True)),
                ("documentation_url", models.URLField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentationFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_path", models.CharField(max_length=500, unique=True)),
                ("language", models.CharField(default="python", max_length=50)),
                ("docstrings", models.JSONField(default=dict, help_text="Extracted docstrings")),
                ("comments", models.JSONField(default=list, help_text="Extracted comments")),
                ("markdown_content", models.TextField(help_text="Generated markdown documentation")),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
            ],
            options={
                "ordering": ["file_path"],
            },
        ),
        migrations.CreateModel(
            name="IssueTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("about", models.TextField(help_text="Description of what this template is for")),
                ("title_prefix", models.CharField(default="[Generated]: ", max_length=100)),
                ("labels", models.JSONField(default=list, help_text="List of labels to apply")),
                ("prompt", models.TextField(help_text="AI instructions for generating content")),
                ("template_body", models.TextField(help_text="Markdown template structure")),
                ("include_files", models.JSONField(default=list, help_text="Files to include as context")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PromptDataset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["prompt", "name"],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Model identifier (e.g., gpt-4o, grok-beta)", max_length=100
                    ),
                ),
                ("display_name", models.CharField(help_text="Human-readable name", max_length=150)),
                (
                    "capabilities",
                    models.JSONField(default=list, help_text="List of capabilities (chat, embedding, etc.)"),
                ),
                ("max_tokens", models.IntegerField(help_text="Maximum tokens this model supports")),
                ("context_window", models.IntegerField(help_text="Context window size")),
                ("supports_system_prompt", models.BooleanField(default=True)),
                ("supports_streaming", models.BooleanField(default=True)),
                (
                    "input_price_per_million",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Input token price per 1M tokens (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "output_price_per_million",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Output token price per 1M tokens (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_default", models.BooleanField(default=False, help_text="Default model for this provider")),
                ("description", models.TextField(blank=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("deprecation_date", models.DateField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="models", to="core.aiprovider"
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "-is_default", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("system_prompt", models.TextField()),
                ("user_prompt", models.TextField()),
                ("response_content", models.TextField()),
                ("model", models.CharField(default="gpt-4o-mini", max_length=50)),
                (
                    "provider",
                    models.CharField(default="openai", help_text="AI provider used (openai, xai, etc.)", max_length=20),
                ),
                ("temperature", models.FloatField(default=0.2)),
                ("max_tokens", models.IntegerField(default=2500)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("cache_hit_count", models.IntegerField(default=0)),
                (
                    "ai_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="AI model used for this response",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cached_responses",
                        to="core.aimodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APILog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_type",
                    models.CharField(choices=[("ai", "AI"), ("github", "GitHub")], db_index=True, max_length=20),
                ),
                ("endpoint", models.CharField(max_length=500)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.IntegerField(blank=True, help_text="Request duration in milliseconds", null=True),
                ),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["api_type", "-created_at"], name="core_apilog_api_typ_724c9b_idx"),
                    models.Index(fields=["status_code", "-created_at"], name="core_apilog_status__2a0c99_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangelogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("commit", "Commit"), ("pr", "Pull Request"), ("manual", "Manual")],
                        default="commit",
                        max_length=20,
                    ),
                ),
                ("commit_sha", models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ("pr_number", models.IntegerField(blank=True, db_index=True, null=True)),
                ("commit_message", models.TextField(blank=True, null=True)),
                ("diff_summary", models.TextField(blank=True, null=True)),
                ("ai_generated_content", models.TextField()),
                ("file_path", models.CharField(default="CHANGELOG_AI.md", max_length=500)),
            ],
            options={
                "verbose_name_plural": "Changelog Entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["entry_type", "-created_at"], name="core_change_entry_t_294187_idx"),
                    models.Index(fields=["commit_sha"], name="core_change_commit__8c0207_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("github_issue_number", models.IntegerField(db_index=True)),
                ("github_repo", models.CharField(default="bamr87/githubai", max_length=200)),
                ("title", models.CharField(max_length=500)),
                ("body", models.TextField()),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("feature", "Feature Request"),
                            ("bug", "Bug Report"),
                            ("readme", "README Update"),
                            ("sub_issue", "Sub-Issue"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("labels", models.JSONField(default=list)),
                ("state", models.CharField(default="open", max_length=20)),
                ("ai_generated", models.BooleanField(default=False)),
                ("ai_prompt_used", models.TextField(blank=True, null=True)),
                ("ai_response", models.TextField(blank=True, null=True)),
                ("html_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "parent_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_issues",
                        to="core.issue",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="core.issuetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueFileReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_path", models.CharField(max_length=500)),
                ("content", models.TextField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="file_references", to="core.issue"
                    ),
                ),
            ],
            options={
                "ordering": ["file_path"],
            },
        ),
        migrations.CreateModel(
            name="PromptDatasetEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_variables",
                    models.JSONField(
                        help_text='Variables to render in the prompt template (e.g., {"repo": "owner/repo", "issue_number": 123})'
                    ),
                ),
                (
                    "expected_output_pattern",
                    models.TextField(blank=True, help_text="Expected output pattern or keywords to validate against"),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text='Tags for filtering test cases (e.g., ["edge_case", "regression"])'
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="core.promptdataset"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Prompt Dataset Entries",
                "ordering": ["dataset", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("auto_issue", "Auto Issue"),
                            ("sub_issue", "Sub-Issue"),
                            ("readme_update", "README Update"),
                            ("documentation", "Documentation"),
                            ("changelog", "Changelog"),
                            ("feedback_issue", "Feedback Issue"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(help_text="Description of what this prompt does")),
                ("system_prompt", models.TextField(help_text="System instructions for AI")),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="User prompt template with Jinja2 variables (e.g., {{ repo }}, {{ issue_number }})"
                    ),
                ),
                ("model", models.CharField(default="gpt-4o-mini", max_length=50)),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("xai", "XAI (Grok)"), ("auto", "Auto (Use Default)")],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("temperature", models.FloatField(default=0.2)),
                ("max_tokens", models.IntegerField(default=2500)),
                ("version_number", models.IntegerField(default=1, help_text="Version number for this prompt")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("usage_count", models.IntegerField(default=0, help_text="Number of times this prompt has been used")),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="AI model to use for this prompt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_templates",
                        to="core.aimodel",
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous version of this prompt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="core.prompttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name", "-version_number"],
            },
        ),
        migrations.CreateModel(
            name="PromptSchema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schema_type",
                    models.CharField(
                        choices=[
                            ("json_schema", "JSON Schema"),
                            ("regex", "Regular Expression"),
                            ("custom", "Custom Validation"),
                        ],
                        default="json_schema",
                        max_length=20,
                    ),
                ),
                ("schema_definition", models.JSONField(help_text="JSON Schema definition or validation rules")),
                ("validation_enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="schemas", to="core.prompttemplate"
                    ),
                ),
            ],
            options={
                "ordering": ["prompt", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_variables",
                    models.JSONField(blank=True, help_text="Variables used to render the prompt", null=True),
                ),
                ("rendered_system_prompt", models.TextField()),
                ("rendered_user_prompt", models.TextField()),
                ("output_content", models.TextField()),
                ("provider_used", models.CharField(max_length=20)),
                ("model_used", models.CharField(max_length=50)),
                ("temperature_used", models.FloatField()),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("cache_hit", models.BooleanField(default=False)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("user_feedback_rating", models.IntegerField(blank=True, help_text="User rating 1-5 stars", null=True)),
                ("validation_passed", models.BooleanField(blank=True, null=True)),
                (
                    "ai_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="AI model used for this execution",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="core.aimodel",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="executions", to="core.prompttemplate"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="promptdataset",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="datasets", to="core.prompttemplate"
            ),
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.CharField(db_index=True, max_length=20, unique=True)),
                ("major", models.IntegerField()),
                ("minor", models.IntegerField()),
                ("patch", models.IntegerField()),
                (
                    "bump_type",
                    models.CharField(
                        choices=[("major", "Major"), ("minor", "Minor"), ("patch", "Patch")], max_length=10
                    ),
                ),
                ("commit_sha", models.CharField(blank=True, max_length=40, null=True)),
                ("commit_message", models.TextField(blank=True, null=True)),
                ("git_tag", models.CharField(blank=True, max_length=50, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["-major", "-minor", "-patch"], name="core_versio_major_481e1c_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(fields=["provider", "is_active"], name="core_aimode_provide_3cb8b9_idx"),
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(fields=["is_default", "is_active"], name="core_aimode_is_defa_bb78d6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="aimodel",
            unique_together={("provider", "name")},
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(fields=["prompt_hash"], name="core_airesp_prompt__e1f400_idx"),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(fields=["provider", "-created_at"], name="core_airesp_provide_1e174a_idx"),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(fields=["-created_at"], name="core_airesp_created_3fea0e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="issuefilereference",
            unique_together={("issue", "file_path")},
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["github_repo", "github_issue_number"], name="core_issue_github__87cf17_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["issue_type", "-created_at"], name="core_issue_issue_t_70387a_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["state", "-created_at"], name="core_issue_state_5b8ff1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="issue",
            unique_together={("github_repo", "github_issue_number")},
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(fields=["category", "is_active"], name="core_prompt_categor_ad7382_idx"),
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(fields=["name", "-version_number"], name="core_prompt_name_280a99_idx"),
        ),
        migrations.AddIndex(
            model_name="promptexecution",
            index=models.Index(fields=["prompt", "-created_at"], name="core_prompt_prompt__e391cd_idx"),
        ),
        migrations.AddIndex(
            model_name="promptexecution",
            index=models.Index(fields=["success", "-created_at"], name="core_prompt_success_f01c2d_idx"),
        ),
        migrations.AddIndex(
            model_name="promptexecution",
            index=models.Index(fields=["cache_hit", "-created_at"], name="core_prompt_cache_h_51fd41_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="promptdataset",
            unique_together={("prompt", "name")},
        ),
    ]
