# Generated by Django 4.2.7 on 2025-11-22 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentationFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_path", models.CharField(max_length=500, unique=True)),
                ("language", models.CharField(default="python", max_length=50)),
                ("docstrings", models.JSONField(default=dict, help_text="Extracted docstrings")),
                ("comments", models.JSONField(default=list, help_text="Extracted comments")),
                ("markdown_content", models.TextField(help_text="Generated markdown documentation")),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
            ],
            options={
                "ordering": ["file_path"],
            },
        ),
        migrations.CreateModel(
            name="IssueTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("about", models.TextField(help_text="Description of what this template is for")),
                ("title_prefix", models.CharField(default="[Generated]: ", max_length=100)),
                ("labels", models.JSONField(default=list, help_text="List of labels to apply")),
                ("prompt", models.TextField(help_text="AI instructions for generating content")),
                ("template_body", models.TextField(help_text="Markdown template structure")),
                ("include_files", models.JSONField(default=list, help_text="Files to include as context")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.CharField(db_index=True, max_length=20, unique=True)),
                ("major", models.IntegerField()),
                ("minor", models.IntegerField()),
                ("patch", models.IntegerField()),
                (
                    "bump_type",
                    models.CharField(
                        choices=[("major", "Major"), ("minor", "Minor"), ("patch", "Patch")], max_length=10
                    ),
                ),
                ("commit_sha", models.CharField(blank=True, max_length=40, null=True)),
                ("commit_message", models.TextField(blank=True, null=True)),
                ("git_tag", models.CharField(blank=True, max_length=50, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["-major", "-minor", "-patch"], name="core_versio_major_481e1c_idx")],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("github_issue_number", models.IntegerField(db_index=True)),
                ("github_repo", models.CharField(default="bamr87/githubai", max_length=200)),
                ("title", models.CharField(max_length=500)),
                ("body", models.TextField()),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("feature", "Feature Request"),
                            ("bug", "Bug Report"),
                            ("readme", "README Update"),
                            ("sub_issue", "Sub-Issue"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("labels", models.JSONField(default=list)),
                ("state", models.CharField(default="open", max_length=20)),
                ("ai_generated", models.BooleanField(default=False)),
                ("ai_prompt_used", models.TextField(blank=True, null=True)),
                ("ai_response", models.TextField(blank=True, null=True)),
                ("html_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "parent_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_issues",
                        to="core.issue",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="core.issuetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangelogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("commit", "Commit"), ("pr", "Pull Request"), ("manual", "Manual")],
                        default="commit",
                        max_length=20,
                    ),
                ),
                ("commit_sha", models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ("pr_number", models.IntegerField(blank=True, db_index=True, null=True)),
                ("commit_message", models.TextField(blank=True, null=True)),
                ("diff_summary", models.TextField(blank=True, null=True)),
                ("ai_generated_content", models.TextField()),
                ("file_path", models.CharField(default="CHANGELOG_AI.md", max_length=500)),
            ],
            options={
                "verbose_name_plural": "Changelog Entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["entry_type", "-created_at"], name="core_change_entry_t_294187_idx"),
                    models.Index(fields=["commit_sha"], name="core_change_commit__8c0207_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("system_prompt", models.TextField()),
                ("user_prompt", models.TextField()),
                ("response_content", models.TextField()),
                ("model", models.CharField(default="gpt-4o-mini", max_length=50)),
                ("temperature", models.FloatField(default=0.2)),
                ("max_tokens", models.IntegerField(default=2500)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("cache_hit_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["prompt_hash"], name="core_airesp_prompt__e1f400_idx"),
                    models.Index(fields=["-created_at"], name="core_airesp_created_3fea0e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IssueFileReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_path", models.CharField(max_length=500)),
                ("content", models.TextField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="file_references", to="core.issue"
                    ),
                ),
            ],
            options={
                "ordering": ["file_path"],
                "unique_together": {("issue", "file_path")},
            },
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["github_repo", "github_issue_number"], name="core_issue_github__87cf17_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["issue_type", "-created_at"], name="core_issue_issue_t_70387a_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["state", "-created_at"], name="core_issue_state_5b8ff1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="issue",
            unique_together={("github_repo", "github_issue_number")},
        ),
    ]
