# Generated by Django 4.2.7 on 2025-11-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_documentationfile_issuetemplate_version_issue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apilog",
            name="api_type",
            field=models.CharField(choices=[("ai", "AI"), ("github", "GitHub")], db_index=True, max_length=20),
        ),
    ]
