# Generated by Django 4.2.7 on 2025-11-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_apilog_api_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="airesponse",
            name="provider",
            field=models.CharField(default="openai", help_text="AI provider used (openai, xai, etc.)", max_length=20),
        ),
        migrations.AddIndex(
            model_name="airesponse",
            index=models.Index(fields=["provider", "-created_at"], name="core_airesp_provide_1e174a_idx"),
        ),
    ]
