# Generated by Django 4.2.7 on 2025-11-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_airesponse_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptDataset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["prompt", "name"],
            },
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("auto_issue", "Auto Issue"),
                            ("sub_issue", "Sub-Issue"),
                            ("readme_update", "README Update"),
                            ("documentation", "Documentation"),
                            ("changelog", "Changelog"),
                            ("feedback_issue", "Feedback Issue"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(help_text="Description of what this prompt does")),
                ("system_prompt", models.TextField(help_text="System instructions for AI")),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="User prompt template with Jinja2 variables (e.g., {{ repo }}, {{ issue_number }})"
                    ),
                ),
                ("model", models.CharField(default="gpt-4o-mini", max_length=50)),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("xai", "XAI (Grok)"), ("auto", "Auto (Use Default)")],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("temperature", models.FloatField(default=0.2)),
                ("max_tokens", models.IntegerField(default=2500)),
                ("version_number", models.IntegerField(default=1, help_text="Version number for this prompt")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("usage_count", models.IntegerField(default=0, help_text="Number of times this prompt has been used")),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous version of this prompt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="core.prompttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name", "-version_number"],
            },
        ),
        migrations.CreateModel(
            name="PromptSchema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schema_type",
                    models.CharField(
                        choices=[
                            ("json_schema", "JSON Schema"),
                            ("regex", "Regular Expression"),
                            ("custom", "Custom Validation"),
                        ],
                        default="json_schema",
                        max_length=20,
                    ),
                ),
                ("schema_definition", models.JSONField(help_text="JSON Schema definition or validation rules")),
                ("validation_enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="schemas", to="core.prompttemplate"
                    ),
                ),
            ],
            options={
                "ordering": ["prompt", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_variables",
                    models.JSONField(blank=True, help_text="Variables used to render the prompt", null=True),
                ),
                ("rendered_system_prompt", models.TextField()),
                ("rendered_user_prompt", models.TextField()),
                ("output_content", models.TextField()),
                ("provider_used", models.CharField(max_length=20)),
                ("model_used", models.CharField(max_length=50)),
                ("temperature_used", models.FloatField()),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("cache_hit", models.BooleanField(default=False)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("user_feedback_rating", models.IntegerField(blank=True, help_text="User rating 1-5 stars", null=True)),
                ("validation_passed", models.BooleanField(blank=True, null=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="executions", to="core.prompttemplate"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptDatasetEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_variables",
                    models.JSONField(
                        help_text='Variables to render in the prompt template (e.g., {"repo": "owner/repo", "issue_number": 123})'
                    ),
                ),
                (
                    "expected_output_pattern",
                    models.TextField(blank=True, help_text="Expected output pattern or keywords to validate against"),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text='Tags for filtering test cases (e.g., ["edge_case", "regression"])'
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="core.promptdataset"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Prompt Dataset Entries",
                "ordering": ["dataset", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="promptdataset",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="datasets", to="core.prompttemplate"
            ),
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(fields=["category", "is_active"], name="core_prompt_categor_ad7382_idx"),
        ),
        migrations.AddIndex(
            model_name="prompttemplate",
            index=models.Index(fields=["name", "-version_number"], name="core_prompt_name_280a99_idx"),
        ),
        migrations.AddIndex(
            model_name="promptexecution",
            index=models.Index(fields=["prompt", "-created_at"], name="core_prompt_prompt__e391cd_idx"),
        ),
        migrations.AddIndex(
            model_name="promptexecution",
            index=models.Index(fields=["success", "-created_at"], name="core_prompt_success_f01c2d_idx"),
        ),
        migrations.AddIndex(
            model_name="promptexecution",
            index=models.Index(fields=["cache_hit", "-created_at"], name="core_prompt_cache_h_51fd41_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="promptdataset",
            unique_together={("prompt", "name")},
        ),
    ]
