# Generated by Django 4.2.7 on 2025-11-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_promptdataset_prompttemplate_promptschema_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Provider name (e.g., openai, xai)", max_length=50, unique=True
                    ),
                ),
                ("display_name", models.CharField(help_text="Human-readable name (e.g., OpenAI, XAI)", max_length=100)),
                (
                    "api_key",
                    models.CharField(blank=True, help_text="API key (encrypted in production)", max_length=500),
                ),
                ("base_url", models.URLField(help_text="API base URL", max_length=500)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "default_temperature",
                    models.FloatField(default=0.2, help_text="Default temperature for this provider"),
                ),
                (
                    "default_max_tokens",
                    models.IntegerField(default=2500, help_text="Default max tokens for this provider"),
                ),
                ("description", models.TextField(blank=True)),
                ("documentation_url", models.URLField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Model identifier (e.g., gpt-4o, grok-beta)", max_length=100
                    ),
                ),
                ("display_name", models.CharField(help_text="Human-readable name", max_length=150)),
                (
                    "capabilities",
                    models.JSONField(default=list, help_text="List of capabilities (chat, embedding, etc.)"),
                ),
                ("max_tokens", models.IntegerField(help_text="Maximum tokens this model supports")),
                ("context_window", models.IntegerField(help_text="Context window size")),
                ("supports_system_prompt", models.BooleanField(default=True)),
                ("supports_streaming", models.BooleanField(default=True)),
                (
                    "input_price_per_million",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Input token price per 1M tokens (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "output_price_per_million",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Output token price per 1M tokens (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_default", models.BooleanField(default=False, help_text="Default model for this provider")),
                ("description", models.TextField(blank=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("deprecation_date", models.DateField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="models", to="core.aiprovider"
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "-is_default", "display_name"],
            },
        ),
        migrations.AddField(
            model_name="airesponse",
            name="ai_model",
            field=models.ForeignKey(
                blank=True,
                help_text="AI model used for this response",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cached_responses",
                to="core.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="promptexecution",
            name="ai_model",
            field=models.ForeignKey(
                blank=True,
                help_text="AI model used for this execution",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="core.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="ai_model",
            field=models.ForeignKey(
                blank=True,
                help_text="AI model to use for this prompt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompt_templates",
                to="core.aimodel",
            ),
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(fields=["provider", "is_active"], name="core_aimode_provide_3cb8b9_idx"),
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(fields=["is_default", "is_active"], name="core_aimode_is_defa_bb78d6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="aimodel",
            unique_together={("provider", "name")},
        ),
    ]
