# Generated by Django 5.1.14 on 2025-11-28 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PRDState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("repo", models.CharField(db_index=True, help_text="GitHub repository (owner/repo)", max_length=255)),
                ("file_path", models.CharField(default="PRD.md", help_text="Path to PRD file in repo", max_length=500)),
                ("content", models.TextField(blank=True, help_text="Current PRD content (Markdown)")),
                ("content_hash", models.CharField(blank=True, help_text="SHA256 hash of content", max_length=64)),
                ("version", models.CharField(default="1.0.0", help_text="PRD version", max_length=50)),
                (
                    "is_locked",
                    models.BooleanField(db_index=True, default=False, help_text="Zero-touch mode - no human edits"),
                ),
                ("last_distilled_at", models.DateTimeField(blank=True, help_text="Last distillation time", null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, help_text="Last GitHub sync time", null=True)),
                ("auto_evolve", models.BooleanField(default=True, help_text="Auto-evolve on repo changes")),
                ("slack_webhook", models.URLField(blank=True, help_text="Slack webhook for alerts", max_length=500)),
            ],
            options={
                "verbose_name": "PRD State",
                "verbose_name_plural": "PRD States",
                "ordering": ["-updated_at"],
                "unique_together": {("repo", "file_path")},
            },
        ),
        migrations.CreateModel(
            name="PRDVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(help_text="Version number", max_length=50)),
                ("content", models.TextField(help_text="PRD content at this version")),
                ("content_hash", models.CharField(help_text="SHA256 hash", max_length=64)),
                ("change_summary", models.TextField(blank=True, help_text="AI-generated change summary")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Generation"),
                            ("commit", "Git Commit"),
                            ("pr_merge", "PR Merge"),
                            ("issue_created", "Issue Created"),
                            ("issue_closed", "Issue Closed"),
                            ("manual_sync", "Manual Sync"),
                            ("scheduled", "Scheduled Distillation"),
                            ("human_edit", "Human Edit"),
                            ("revert", "Revert"),
                            ("export", "Export to Issues"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("trigger_ref", models.CharField(blank=True, help_text="Commit SHA, issue #, etc.", max_length=255)),
                ("is_human_edit", models.BooleanField(db_index=True, default=False)),
                (
                    "prd_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="prd_machine.prdstate"
                    ),
                ),
                (
                    "reverted_to",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="prd_machine.prdversion"
                    ),
                ),
            ],
            options={
                "verbose_name": "PRD Version",
                "verbose_name_plural": "PRD Versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PRDExport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("issues", "GitHub Issues"),
                            ("changelog", "Changelog Entry"),
                            ("version_bump", "Version Bump"),
                            ("milestone", "GitHub Milestone"),
                            ("all", "Full Export"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("items_created", models.IntegerField(default=0, help_text="Number of items created")),
                ("details", models.JSONField(default=dict, help_text="Export details")),
                ("github_refs", models.JSONField(default=list, help_text="GitHub issue/PR numbers created")),
                (
                    "prd_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="exports", to="prd_machine.prdstate"
                    ),
                ),
                (
                    "prd_version",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="prd_machine.prdversion"
                    ),
                ),
            ],
            options={
                "verbose_name": "PRD Export",
                "verbose_name_plural": "PRD Exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PRDEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("push", "Push to Branch"),
                            ("pull_request", "Pull Request"),
                            ("issues", "Issue Event"),
                            ("issue_comment", "Issue Comment"),
                            ("release", "Release"),
                            ("workflow_run", "Workflow Run"),
                            ("manual", "Manual Trigger"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("event_data", models.JSONField(default=dict, help_text="Event payload")),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.TextField(blank=True, help_text="Processing result or error")),
                (
                    "prd_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="prd_machine.prdstate"
                    ),
                ),
            ],
            options={
                "verbose_name": "PRD Event",
                "verbose_name_plural": "PRD Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["processed", "-created_at"], name="prd_machine_process_2df3e1_idx"),
                    models.Index(fields=["event_type", "processed"], name="prd_machine_event_t_d77e84_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PRDConflict",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("outdated_api", "API Documentation Outdated"),
                            ("missing_feature", "Feature in Code Not in PRD"),
                            ("orphan_requirement", "Requirement Not Implemented"),
                            ("deadline_missed", "Milestone Deadline Missed"),
                            ("version_mismatch", "Version Number Mismatch"),
                            ("metric_drift", "Metric Target Drift"),
                            ("dependency_change", "Dependency Changed"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(help_text="Conflict description")),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("section_affected", models.CharField(blank=True, help_text="PRD section affected", max_length=50)),
                ("suggested_resolution", models.TextField(blank=True, help_text="AI-suggested resolution")),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.CharField(blank=True, help_text="Auto/Manual + details", max_length=255)),
                ("slack_notified", models.BooleanField(default=False)),
                (
                    "prd_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="conflicts", to="prd_machine.prdstate"
                    ),
                ),
            ],
            options={
                "verbose_name": "PRD Conflict",
                "verbose_name_plural": "PRD Conflicts",
                "ordering": ["-severity", "-created_at"],
                "indexes": [
                    models.Index(fields=["resolved", "severity"], name="prd_machine_resolve_8927e4_idx"),
                    models.Index(fields=["conflict_type", "resolved"], name="prd_machine_conflic_ee5376_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="prdversion",
            index=models.Index(fields=["prd_state", "-created_at"], name="prd_machine_prd_sta_7c33a7_idx"),
        ),
        migrations.AddIndex(
            model_name="prdversion",
            index=models.Index(fields=["trigger_type", "-created_at"], name="prd_machine_trigger_67d2bb_idx"),
        ),
    ]
