# Generated by Django 5.1.14 on 2025-11-30 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prd_machine", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prdstate",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Document State",
                "verbose_name_plural": "Document States",
            },
        ),
        migrations.AddField(
            model_name="prdstate",
            name="document_type",
            field=models.CharField(
                choices=[("prd", "Product Requirements Document"), ("readme", "README"), ("ip", "Implementation Plan")],
                db_index=True,
                default="prd",
                help_text="Type of document",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="prdstate",
            name="last_aligned_at",
            field=models.DateTimeField(blank=True, help_text="Last cross-document alignment time", null=True),
        ),
        migrations.AddField(
            model_name="prdstate",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Source document for sync (e.g., README derives from PRD)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_documents",
                to="prd_machine.prdstate",
            ),
        ),
        migrations.AlterField(
            model_name="prdstate",
            name="content",
            field=models.TextField(blank=True, help_text="Current document content (Markdown)"),
        ),
        migrations.AlterField(
            model_name="prdstate",
            name="file_path",
            field=models.CharField(default="PRD.md", help_text="Path to document file in repo", max_length=500),
        ),
        migrations.AlterField(
            model_name="prdstate",
            name="version",
            field=models.CharField(default="1.0.0", help_text="Document version", max_length=50),
        ),
        migrations.AddIndex(
            model_name="prdstate",
            index=models.Index(fields=["repo", "document_type"], name="prd_machine_repo_cd155e_idx"),
        ),
    ]
